-- SAS seed data. Demo password for ALL accounts: Password123!
-- Generated by scripts/gen-seed.mjs — do not edit by hand.

DELETE FROM subscription_plans;
INSERT INTO subscription_plans (id,name,code,price_monthly,currency,max_students,max_teachers,storage_mb,features,is_custom,is_active,sort_order) VALUES ('plan_free','Free','free',0,'NGN',50,5,500,'["academics","attendance","announcements"]',0,1,0);
INSERT INTO subscription_plans (id,name,code,price_monthly,currency,max_students,max_teachers,storage_mb,features,is_custom,is_active,sort_order) VALUES ('plan_starter','Starter','starter',15000,'NGN',300,20,5000,'["academics","attendance","results","fees","announcements","cbt"]',0,1,1);
INSERT INTO subscription_plans (id,name,code,price_monthly,currency,max_students,max_teachers,storage_mb,features,is_custom,is_active,sort_order) VALUES ('plan_professional','Professional','professional',35000,'NGN',1500,100,20000,'["academics","attendance","results","fees","accounting","cbt","inventory","pos","reports"]',0,1,2);
INSERT INTO subscription_plans (id,name,code,price_monthly,currency,max_students,max_teachers,storage_mb,features,is_custom,is_active,sort_order) VALUES ('plan_enterprise','Enterprise','enterprise',0,'NGN',NULL,NULL,NULL,'["all"]',1,1,3);

INSERT INTO schools (id,name,short_name,slug,email,phone,address,primary_color,secondary_color,status) VALUES ('sch_demo000000000000000000000001','Greenfield Academy','Greenfield','greenfield','info@greenfield.edu','+234 800 000 0000','12 Palm Avenue, Lagos','#16a34a','#15803d','active');
INSERT INTO subscriptions (id,school_id,plan_id,status,trial_ends_at,current_period_end) VALUES ('sub_demo01','sch_demo000000000000000000000001','plan_professional','active','2026-08-31T15:51:45.488Z','2026-08-31T15:51:45.488Z');

INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_super',NULL,'super_admin','Platform','Owner','super@sas.app','pbkdf2$100000$4vcGzYgaJ07ZzkBMN1BJHg==$REXghNPSzIyskWN4uQk82NdWDeDdMoVue28K7CSahz4=',1);
INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_admin','sch_demo000000000000000000000001','school_admin','Grace','Adeyemi','admin@greenfield.edu','pbkdf2$100000$dJKS5B6WyvMSUK9lnf26jA==$LpGs5I0Xuq7GvcNNVfSg5A7ijufPZy1wbUTeMeSm4c8=',1);
INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_teacher','sch_demo000000000000000000000001','teacher','John','Okafor','teacher@greenfield.edu','pbkdf2$100000$3lpGtlyOh1CqLvmfyBnzWQ==$gfXdtisPqkRyMUNtWTjoeHl245eO+81dpJ91JUn2BhY=',1);
INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_student','sch_demo000000000000000000000001','student','Mary','Bello','student@greenfield.edu','pbkdf2$100000$vUv6//OuWKW2dDGzMIr2ew==$Guhyhwyi5oSPBkDM3oEOilBpV/ZxFgmRE4+gZU5Bpkw=',1);
INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_sales','sch_demo000000000000000000000001','sales_staff','Peter','Nwosu','sales@greenfield.edu','pbkdf2$100000$Pa+TBpfWSlpWwP0CSqwvbA==$nsFBuJlwyCmcKl/StLgrlPfQdxWcOGJaqkKjNMhu/xs=',1);

INSERT INTO sessions_academic (id,school_id,name,is_current) VALUES ('ses_2025','sch_demo000000000000000000000001','2025/2026',1);
INSERT INTO terms (id,school_id,session_id,name,is_current) VALUES ('trm_1','sch_demo000000000000000000000001','ses_2025','First Term',1);
INSERT INTO terms (id,school_id,session_id,name,is_current) VALUES ('trm_2','sch_demo000000000000000000000001','ses_2025','Second Term',0);

INSERT INTO classes (id,school_id,name,level,teacher_id) VALUES ('cls_jss1','sch_demo000000000000000000000001','JSS 1','Junior','usr_teacher');
INSERT INTO classes (id,school_id,name,level,teacher_id) VALUES ('cls_jss2','sch_demo000000000000000000000001','JSS 2','Junior','usr_teacher');
INSERT INTO classes (id,school_id,name,level,teacher_id) VALUES ('cls_ss1','sch_demo000000000000000000000001','SS 1','Senior','usr_teacher');

INSERT INTO subjects (id,school_id,name,code) VALUES ('subj_math','sch_demo000000000000000000000001','Mathematics','MTH');
INSERT INTO subjects (id,school_id,name,code) VALUES ('subj_eng','sch_demo000000000000000000000001','English','ENG');
INSERT INTO subjects (id,school_id,name,code) VALUES ('subj_sci','sch_demo000000000000000000000001','Basic Science','SCI');
INSERT INTO subjects (id,school_id,name,code) VALUES ('subj_soc','sch_demo000000000000000000000001','Social Studies','SOC');

INSERT INTO students (id,school_id,user_id,admission_no,first_name,last_name,gender,class_id,guardian_name,guardian_phone,status) VALUES ('std_1','sch_demo000000000000000000000001','usr_student','GA/001','Mary','Bello','F','cls_jss1','Guardian','+234800111222','active');
INSERT INTO students (id,school_id,user_id,admission_no,first_name,last_name,gender,class_id,guardian_name,guardian_phone,status) VALUES ('std_2','sch_demo000000000000000000000001',NULL,'GA/002','Samuel','Eze','M','cls_jss1','Guardian','+234800111222','active');
INSERT INTO students (id,school_id,user_id,admission_no,first_name,last_name,gender,class_id,guardian_name,guardian_phone,status) VALUES ('std_3','sch_demo000000000000000000000001',NULL,'GA/003','Aisha','Yusuf','F','cls_jss2','Guardian','+234800111222','active');
INSERT INTO students (id,school_id,user_id,admission_no,first_name,last_name,gender,class_id,guardian_name,guardian_phone,status) VALUES ('std_4','sch_demo000000000000000000000001',NULL,'GA/004','David','Okon','M','cls_ss1','Guardian','+234800111222','active');

INSERT INTO teachers (id,school_id,user_id,first_name,last_name,email,subject,employee_no,status) VALUES ('tch_1','sch_demo000000000000000000000001','usr_teacher','John','Okafor','teacher@greenfield.edu','Mathematics','EMP/001','active');
INSERT INTO teachers (id,school_id,first_name,last_name,email,subject,employee_no,status) VALUES ('tch_2','sch_demo000000000000000000000001','Ngozi','Ibe','ngozi@greenfield.edu','English','EMP/002','active');

INSERT INTO fee_structures (id,school_id,name,category,amount,term_id) VALUES ('fee_tuition','sch_demo000000000000000000000001','Tuition','tuition',50000,'trm_1');
INSERT INTO fee_structures (id,school_id,name,category,amount,term_id) VALUES ('fee_exam','sch_demo000000000000000000000001','Examination','examination',5000,'trm_1');
INSERT INTO student_fees (id,school_id,student_id,fee_id,amount,amount_paid,status) VALUES ('sf_1','sch_demo000000000000000000000001','std_1','fee_tuition',50000,30000,'partial');
INSERT INTO student_fees (id,school_id,student_id,fee_id,amount,amount_paid,status) VALUES ('sf_2','sch_demo000000000000000000000001','std_1','fee_exam',5000,5000,'paid');

INSERT INTO products (id,school_id,name,category,purchase_price,selling_price,stock_qty,low_stock) VALUES ('prod_1','sch_demo000000000000000000000001','Exercise Book','Stationery',150,250,200,10);
INSERT INTO products (id,school_id,name,category,purchase_price,selling_price,stock_qty,low_stock) VALUES ('prod_2','sch_demo000000000000000000000001','School Uniform','Uniform',3500,5000,60,10);
INSERT INTO products (id,school_id,name,category,purchase_price,selling_price,stock_qty,low_stock) VALUES ('prod_3','sch_demo000000000000000000000001','School Bag','Accessories',2500,4000,8,10);

INSERT INTO announcements (id,school_id,title,body,audience,created_by) VALUES ('ann_1','sch_demo000000000000000000000001','Resumption Date','School resumes Monday, September 15th for the new term.','all','usr_admin');
INSERT INTO announcements (id,school_id,title,body,audience,created_by) VALUES ('ann_2','sch_demo000000000000000000000001','PTA Meeting','The termly PTA meeting holds this Saturday by 10am.','parents','usr_admin');

INSERT INTO transactions (id,school_id,type,category,description,amount) VALUES ('txn_seed1','sch_demo000000000000000000000001','income','fees','Opening fee collections',450000);
INSERT INTO transactions (id,school_id,type,category,description,amount) VALUES ('txn_seed2','sch_demo000000000000000000000001','expense','salaries','Staff salaries',180000);

INSERT INTO results (id,school_id,student_id,subject_id,class_id,term_id,ca_score,exam_score,total_score,grade,remark,status,entered_by) VALUES ('res_1','sch_demo000000000000000000000001','std_1','subj_math','cls_jss1','trm_1',28,55,83,'A','Excellent','approved','usr_teacher');
INSERT INTO results (id,school_id,student_id,subject_id,class_id,term_id,ca_score,exam_score,total_score,grade,remark,status,entered_by) VALUES ('res_2','sch_demo000000000000000000000001','std_1','subj_eng','cls_jss1','trm_1',22,45,67,'B','Very Good','approved','usr_teacher');
