// Generates schema/seed.sql with real PBKDF2 password hashes that match
// functions/_server/crypto.ts (pbkdf2$100000$<saltB64>$<hashB64>, SHA-256, 32 bytes).
import { pbkdf2Sync, randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";

const ITER = 100_000;
function hash(pw) {
  const salt = randomBytes(16);
  const dk = pbkdf2Sync(pw, salt, ITER, 32, "sha256");
  return `pbkdf2$${ITER}$${salt.toString("base64")}$${dk.toString("base64")}`;
}

const PW = "Password123!";
const q = (s) => (s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`);

const superPw = hash(PW);
const adminPw = hash(PW);
const teacherPw = hash(PW);
const studentPw = hash(PW);
const salesPw = hash(PW);

const SCHOOL = "sch_demo000000000000000000000001";
const trialEnds = new Date(Date.now() + 14 * 864e5).toISOString();

const lines = [];
lines.push("-- SAS seed data. Demo password for ALL accounts: Password123!");
lines.push("-- Generated by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("");

// Plans
lines.push("DELETE FROM subscription_plans;");
const plans = [
  ["plan_free", "Free", "free", 0, 50, 5, 500, '["academics","attendance","announcements"]', 0, 0],
  ["plan_starter", "Starter", "starter", 15000, 300, 20, 5000, '["academics","attendance","results","fees","announcements","cbt"]', 0, 1],
  ["plan_professional", "Professional", "professional", 35000, 1500, 100, 20000, '["academics","attendance","results","fees","accounting","cbt","inventory","pos","reports"]', 0, 2],
  ["plan_enterprise", "Enterprise", "enterprise", 0, null, null, null, '["all"]', 1, 3],
];
for (const [id, name, code, price, maxS, maxT, storage, feats, custom, sort] of plans) {
  lines.push(
    `INSERT INTO subscription_plans (id,name,code,price_monthly,currency,max_students,max_teachers,storage_mb,features,is_custom,is_active,sort_order) VALUES (${q(id)},${q(name)},${q(code)},${price},'NGN',${maxS ?? "NULL"},${maxT ?? "NULL"},${storage ?? "NULL"},${q(feats)},${custom},1,${sort});`,
  );
}
lines.push("");

// Demo school
lines.push(`INSERT INTO schools (id,name,short_name,slug,email,phone,address,primary_color,secondary_color,status) VALUES (${q(SCHOOL)},'Greenfield Academy','Greenfield','greenfield','info@greenfield.edu','+234 800 000 0000','12 Palm Avenue, Lagos','#16a34a','#15803d','active');`);
lines.push(`INSERT INTO subscriptions (id,school_id,plan_id,status,trial_ends_at,current_period_end) VALUES ('sub_demo01',${q(SCHOOL)},'plan_professional','active',${q(trialEnds)},${q(trialEnds)});`);
lines.push("");

// Users
lines.push(`INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_super',NULL,'super_admin','Platform','Owner','super@sas.app',${q(superPw)},1);`);
lines.push(`INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_admin',${q(SCHOOL)},'school_admin','Grace','Adeyemi','admin@greenfield.edu',${q(adminPw)},1);`);
lines.push(`INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_teacher',${q(SCHOOL)},'teacher','John','Okafor','teacher@greenfield.edu',${q(teacherPw)},1);`);
lines.push(`INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_student',${q(SCHOOL)},'student','Mary','Bello','student@greenfield.edu',${q(studentPw)},1);`);
lines.push(`INSERT INTO users (id,school_id,role,first_name,last_name,email,password_hash,email_verified) VALUES ('usr_sales',${q(SCHOOL)},'sales_staff','Peter','Nwosu','sales@greenfield.edu',${q(salesPw)},1);`);
lines.push("");

// Academic session + terms
lines.push(`INSERT INTO sessions_academic (id,school_id,name,is_current) VALUES ('ses_2025',${q(SCHOOL)},'2025/2026',1);`);
lines.push(`INSERT INTO terms (id,school_id,session_id,name,is_current) VALUES ('trm_1',${q(SCHOOL)},'ses_2025','First Term',1);`);
lines.push(`INSERT INTO terms (id,school_id,session_id,name,is_current) VALUES ('trm_2',${q(SCHOOL)},'ses_2025','Second Term',0);`);
lines.push("");

// Classes
const classes = [["cls_jss1", "JSS 1", "Junior"], ["cls_jss2", "JSS 2", "Junior"], ["cls_ss1", "SS 1", "Senior"]];
for (const [id, name, level] of classes)
  lines.push(`INSERT INTO classes (id,school_id,name,level,teacher_id) VALUES (${q(id)},${q(SCHOOL)},${q(name)},${q(level)},'usr_teacher');`);
lines.push("");

// Subjects
const subjects = [["subj_math", "Mathematics", "MTH"], ["subj_eng", "English", "ENG"], ["subj_sci", "Basic Science", "SCI"], ["subj_soc", "Social Studies", "SOC"]];
for (const [id, name, code] of subjects)
  lines.push(`INSERT INTO subjects (id,school_id,name,code) VALUES (${q(id)},${q(SCHOOL)},${q(name)},${q(code)});`);
lines.push("");

// Students
const students = [
  ["std_1", "GA/001", "Mary", "Bello", "F", "cls_jss1", "usr_student"],
  ["std_2", "GA/002", "Samuel", "Eze", "M", "cls_jss1", null],
  ["std_3", "GA/003", "Aisha", "Yusuf", "F", "cls_jss2", null],
  ["std_4", "GA/004", "David", "Okon", "M", "cls_ss1", null],
];
for (const [id, adm, fn, ln, g, cls, uidLink] of students)
  lines.push(`INSERT INTO students (id,school_id,user_id,admission_no,first_name,last_name,gender,class_id,guardian_name,guardian_phone,status) VALUES (${q(id)},${q(SCHOOL)},${q(uidLink)},${q(adm)},${q(fn)},${q(ln)},${q(g)},${q(cls)},'Guardian','+234800111222','active');`);
lines.push("");

// Teachers
lines.push(`INSERT INTO teachers (id,school_id,user_id,first_name,last_name,email,subject,employee_no,status) VALUES ('tch_1',${q(SCHOOL)},'usr_teacher','John','Okafor','teacher@greenfield.edu','Mathematics','EMP/001','active');`);
lines.push(`INSERT INTO teachers (id,school_id,first_name,last_name,email,subject,employee_no,status) VALUES ('tch_2',${q(SCHOOL)},'Ngozi','Ibe','ngozi@greenfield.edu','English','EMP/002','active');`);
lines.push("");

// Fee structures
lines.push(`INSERT INTO fee_structures (id,school_id,name,category,amount,term_id) VALUES ('fee_tuition',${q(SCHOOL)},'Tuition','tuition',50000,'trm_1');`);
lines.push(`INSERT INTO fee_structures (id,school_id,name,category,amount,term_id) VALUES ('fee_exam',${q(SCHOOL)},'Examination','examination',5000,'trm_1');`);
lines.push(`INSERT INTO student_fees (id,school_id,student_id,fee_id,amount,amount_paid,status) VALUES ('sf_1',${q(SCHOOL)},'std_1','fee_tuition',50000,30000,'partial');`);
lines.push(`INSERT INTO student_fees (id,school_id,student_id,fee_id,amount,amount_paid,status) VALUES ('sf_2',${q(SCHOOL)},'std_1','fee_exam',5000,5000,'paid');`);
lines.push("");

// Products
const products = [
  ["prod_1", "Exercise Book", "Stationery", 150, 250, 200],
  ["prod_2", "School Uniform", "Uniform", 3500, 5000, 60],
  ["prod_3", "School Bag", "Accessories", 2500, 4000, 8],
];
for (const [id, name, cat, pp, sp, qty] of products)
  lines.push(`INSERT INTO products (id,school_id,name,category,purchase_price,selling_price,stock_qty,low_stock) VALUES (${q(id)},${q(SCHOOL)},${q(name)},${q(cat)},${pp},${sp},${qty},10);`);
lines.push("");

// Announcements
lines.push(`INSERT INTO announcements (id,school_id,title,body,audience,created_by) VALUES ('ann_1',${q(SCHOOL)},'Resumption Date','School resumes Monday, September 15th for the new term.','all','usr_admin');`);
lines.push(`INSERT INTO announcements (id,school_id,title,body,audience,created_by) VALUES ('ann_2',${q(SCHOOL)},'PTA Meeting','The termly PTA meeting holds this Saturday by 10am.','parents','usr_admin');`);
lines.push("");

// A couple of transactions so finance widgets are non-empty
lines.push(`INSERT INTO transactions (id,school_id,type,category,description,amount) VALUES ('txn_seed1',${q(SCHOOL)},'income','fees','Opening fee collections',450000);`);
lines.push(`INSERT INTO transactions (id,school_id,type,category,description,amount) VALUES ('txn_seed2',${q(SCHOOL)},'expense','salaries','Staff salaries',180000);`);
lines.push("");

// Sample results
lines.push(`INSERT INTO results (id,school_id,student_id,subject_id,class_id,term_id,ca_score,exam_score,total_score,grade,remark,status,entered_by) VALUES ('res_1',${q(SCHOOL)},'std_1','subj_math','cls_jss1','trm_1',28,55,83,'A','Excellent','approved','usr_teacher');`);
lines.push(`INSERT INTO results (id,school_id,student_id,subject_id,class_id,term_id,ca_score,exam_score,total_score,grade,remark,status,entered_by) VALUES ('res_2',${q(SCHOOL)},'std_1','subj_eng','cls_jss1','trm_1',22,45,67,'B','Very Good','approved','usr_teacher');`);

writeFileSync(new URL("../schema/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log("Wrote schema/seed.sql");
